// Package models is a package that contains all models
// Author : readyGo "JitenP@Outlook.Com"
// This code is generated by readyGo. You are free to make amendments as and where required
package models
import (
	"errors"
	"regexp"
	"bytes"
	"encoding/gob"
)
// Product type contains all releated fields
	type Product struct {
	Name string `json:"name"  `
	Description string `json:"description"  `
	RefNo int64 `json:"refno"  `
	HasStock bool `json:"hasstock"  `
	Status string `json:"status"  `
	LastModified string `json:"lastmodified"  `
	Address string `json:"address"  `
	ID int `json:"id"  `
	}

// ValidateProduct is to validate Product data. The Validation is based on regex
func ValidateProduct(p *Product)(err error){
var rxDescription=regexp.MustCompile("[a-zA-Z0-9]")
if !rxDescription.MatchString(p.Description) {
	return errors.New("invalid value for given field: Description")
}
	return nil
}

// BytesToProduct is to convert given bytes to the Product object.
func BytesToProduct(b []byte) (*Product, error) {
	t := &Product{}
	dec := gob.NewDecoder(bytes.NewReader(b))
	err := dec.Decode(t)
	if err != nil {
		return nil, err
	}
	return t, nil
}